# Generated by Django 2.2.6 on 2019-10-16 04:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('flag', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('logo', models.URLField()),
                ('country', models.CharField(max_length=50)),
                ('founded', models.IntegerField()),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_surface', models.CharField(max_length=50)),
                ('venue_address', models.CharField(max_length=50)),
                ('venue_city', models.CharField(max_length=50)),
                ('venue_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField()),
                ('league_id', models.IntegerField()),
                ('event_date', models.DateTimeField(null=True)),
                ('event_timestamp', models.DateTimeField(null=True)),
                ('firstHalfStart', models.DateTimeField()),
                ('secondHalfStart', models.DateTimeField()),
                ('roundSeason', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('statusShort', models.CharField(max_length=50)),
                ('elapsed', models.IntegerField()),
                ('venue', models.CharField(max_length=50)),
                ('referee', models.CharField(max_length=50)),
                ('homeTeam', django.contrib.postgres.fields.jsonb.JSONField()),
                ('awayTeam', django.contrib.postgres.fields.jsonb.JSONField()),
                ('goalsHomeTeam', models.IntegerField()),
                ('goalsAwayTeam', models.IntegerField()),
                ('score', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': ['Matches'],
                'ordering': ['-event_date'],
            },
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Match')),
                ('events', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lineups', django.contrib.postgres.fields.jsonb.JSONField()),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField()),
                ('players', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=('core.match',),
        ),
        migrations.DeleteModel(
            name='MatchDetails',
        ),
    ]
