# Generated by Django 2.2.6 on 2019-10-16 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191016_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['country']},
        ),
        migrations.AlterModelOptions(
            name='countryteam',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='match',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='lineups',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fixture_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
