# Generated by Django 2.2.6 on 2019-10-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191020_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryteam',
            name='venue_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_surface',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='firstHalfStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondHalfStart',
            field=models.DateTimeField(null=True),
        ),
    ]
