# Generated by Django 2.2.6 on 2019-10-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191020_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='roundSeason',
            field=models.CharField(max_length=50, verbose_name='round'),
        ),
    ]
