# Generated by Django 2.2.6 on 2019-10-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191021_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='statusShort',
            field=models.CharField(max_length=10),
        ),
    ]
