# Generated by Django 2.2.6 on 2019-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191021_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='flag',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='is_current',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='season',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='season_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='season_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='standings',
            field=models.BooleanField(),
        ),
    ]
