# Generated by Django 2.2.6 on 2019-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191022_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='league_id',
            field=models.IntegerField(unique=True),
        ),
    ]
