# Generated by Django 2.2.6 on 2019-10-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191022_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagues',
            options={'ordering': ['season_start']},
        ),
    ]
