# Generated by Django 2.2.6 on 2019-10-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191022_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagues',
            options={'ordering': ['-season_start']},
        ),
    ]
