# Generated by Django 2.2.6 on 2019-10-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191022_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagues',
            options={},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['event_date'], 'verbose_name_plural': ['Matches']},
        ),
    ]
