# Generated by Django 2.2.6 on 2019-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191022_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='roundSeason',
            field=models.CharField(max_length=100, verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
