# Generated by Django 2.2.6 on 2019-10-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191023_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='venue_surface',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='goalsAwayTeam',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goalsHomeTeam',
            field=models.IntegerField(null=True),
        ),
    ]
