# Generated by Django 2.2.6 on 2019-10-23 10:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191023_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='awayTeam',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
