# Generated by Django 2.2.6 on 2019-10-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191023_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.URLField(null=True),
        ),
    ]
