# Generated by Django 2.2.6 on 2019-10-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191024_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='logo',
            field=models.URLField(null=True),
        ),
    ]
