# Generated by Django 2.2.6 on 2019-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191024_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryteam',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countryteam',
            name='founded',
            field=models.IntegerField(null=True),
        ),
    ]
