# Generated by Django 2.2.6 on 2019-10-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191026_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['event_timestamp'], 'verbose_name_plural': ['Matches']},
        ),
    ]
