# Generated by Django 2.2.6 on 2019-10-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191028_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-event_timestamp'], 'verbose_name_plural': ['Matches']},
        ),
    ]
