# Generated by Django 2.2.6 on 2019-10-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191028_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['event_timestamp'], 'verbose_name_plural': ['Matches']},
        ),
    ]
